version: '3.0'
services:
  mariadb:
    image: mariadb-ubi:10.4.22
    volumes:
      - /var/opt/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file: .env
    restart: always
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 96GB
        reservations:
          cpus: '0.10'
          memory: 100MB
      restart_policy:
        condition: on-failure
        max_attempts: 5
    read_only: true
    tmpfs:
      - /tmp
      - /run
